server:
  port: 28080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minjie
    username: root
    password: yangzl6271!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true

  # 上传文件大小设置
  servlet:
    multipart:
      #设置单个文件大小，单位MB和KB都可以
      max-file-size: 100MB
      #设置总上传的数据大小，单位MB和KB都可以
      max-request-size: 100MB

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  # 配置日志默认输出到控制台，因为Sql语句不可见，要查看日志才可见执行情况
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
    #xml文件位置
  mapper-locations: classpath:mapper/*.xml

#域名设置(为了解决导出数据跨域问题)
access-Control-Allow-Origin: http://localhost:8080/

jwt:
  # openssl rand -base64 256
  secret: gx4SN/4gh6QPvLfVWCW8Aoo4l2n66d2338IwXyu1koDT1W94XS35OZJPYkA2IIMMgmlz96LCHSNc8jLYuzwB1IreKOZz2TZhsWODfjHAS9bYlduniCUSuSPZ5/OP15O63fn1kN1N5w64frpyWcWbTtiCgLMkJpnfjmqFMAr7fgcOGyt2rmunvFYni9T78Q4fn/0gpx3qm8zXw3oBbFb1Ge9Wnh1UCSapXd/EzLau3iaXqp9f+8FHmSCo9vbEaRSRMPHdcpnB4WKHKySE/BCNSsWM+kHmHyrAbvKErPCz2XXMnIalUoAtquq03LnmYjrBHyI230VcYEVzGmzLOTsSJw==
  access_token:
    expiration: 3600
  refresh_token:
    expiration: 604800